### ISSUE TITLE
persistence

### ISSUE THREAD

**Issue by Qurexhi** [dana-at-cp/backdoor-apk#36] opened 2016-09-23 09:13 UTC
brother when Application close meterpreter session close.
please make it persistence or any solution??

**Comment by dana-at-cp** [comment] 2016-09-23 20:52
Yes. Having the session die when the app is closed is expected behavior for now.

I do add a persistence hook that will silently try to reconnect the next time the phone reboots. Try it out. Let me know if it works for you.

**Comment by SNDTiger** [comment] 2016-09-25 06:01
still the same bro session closes after the application exit

**Comment by Qurexhi** [comment] 2016-09-25 18:32
still not work brother session close when app close...

**Comment by dana-at-cp** [comment] 2016-09-26 15:14
@Qurexhi @SNDTiger I think you both missed what I said. It's normal to lose the session when the app closes. In order to persist backdoor access, there is code that will attempt to connect back when the Android device powers on (i.e. upon reboot). Make sure you have the metasploit handler running/listening when the device reboots. You should get a session with no visual indication on the device.

I've tested it and it does in fact work. :)

**Comment by aancw** [comment] 2016-09-27 04:16
Just for reference :) http://null-byte.wonderhowto.com/how-to/create-persistent-back-door-android-using-kali-linux-0161280/

**Comment by Maxnonym** [comment] 2016-09-27 07:37
I have some issue, Failed to sign recompiled APK?
Thank you!!!

**Comment by dana-at-cp** [comment] 2016-09-28 02:46
@aancw The persistence hook featured in backdoor-apk uses a different method.

**Comment by dana-at-cp** [comment] 2016-09-28 02:53
Closing since persistence upon device reboot is already a feature.

**Closed by dana-at-cp** 2016-09-28 02:53 UTC
