### ISSUE TITLE
After inject and install, apllication get "force close

### ISSUE THREAD

**Issue by ichsanrendi24** [dana-at-cp/backdoor-apk#54] opened 2016-11-21 15:09 UTC
hi, i tried to rebuilding infectedapk like as you. but, when i instal that, aplication get force close. i triedwith whatsapp and b612 but it's same get error force close. do you know why ? please help me. thanks

**Comment by dana-at-cp** [comment] 2016-11-22 13:32
@ichsanrendi24 Where did you get the APK files? The source matters quite a bit.

**Comment by maklmakl** [comment] 2016-11-22 23:04
i downloaded from Google 
any recommended sites?

**Comment by dana-at-cp** [comment] 2016-11-28 16:03
@maklmakl I assume from the Google Play store? Also, I'm going to close the issue you created as it appears to be a duplicate of this issue.

**Comment by dana-at-cp** [comment] 2016-11-28 22:18
@ichsanrendi24 @maklmakl I was able to recreate the issue on my updated version of Kali Linux. I can only assume that something changed in Metasploit at this time. I'll look into it ASAP.

**Comment by dana-at-cp** [comment] 2016-11-29 17:19
@ichsanrendi24 @maklmakl Confirmed that something changed in Metasploit and the backdoor-apk code had some breakage as a result. A fix will be out later today.

**Comment by dana-at-cp** [comment] 2016-11-29 17:20
@ichsanrendi24 @maklmakl FYI. If you know how to use 'adb' in the platform tools folder of the Android SDK then you can use 'adb logcat' to get a better idea of why the application is crashing.

**Comment by dana-at-cp** [comment] 2016-11-29 21:18
@ichsanrendi24 @maklmakl Fixed in version 0.1.6 on master.

**Closed by dana-at-cp** 2016-11-29 21:18 UTC
