### ISSUE TITLE
Failed to copy RAT smali files

### ISSUE THREAD

**Issue by Alf-Richards** [dana-at-cp/backdoor-apk#72] opened 2017-01-29 14:23 UTC
Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[!] Failed to copy RAT smali files

**Comment by dana-at-cp** [comment] 2017-01-30 15:28
@Alf-Richards Can you attach your run.log file?

**Comment by dana-at-cp** [comment] 2017-02-03 16:42
@Alf-Richards Any update? I assume your Metasploit version is old.

**Comment by Alf-Richards** [comment] 2017-02-03 16:56
I was updated metasploit. Thak you

**Comment by dana-at-cp** [comment] 2017-02-03 18:33
@Alf-Richards The issue is now resolved?

**Comment by dana-at-cp** [comment] 2017-02-07 16:24
Reporter disengaged. Closing.

**Closed by dana-at-cp** 2017-02-07 16:24 UTC
Labels: invalid
