### ISSUE TITLE
apk file is place in same folder and same problem i have attached with screen shots

### ISSUE THREAD

**Issue by devrajashwin** [dana-at-cp/backdoor-apk#29] opened 2016-08-18 19:24 UTC
see i have al ready did that ..........
and then i runed
./backdoor-apk.sh tubemate_2.2.9.apk

![Uploading Screenshot from 2016-08-19 17-15-48.png…]()

2>TERMINAL
![screenshot from 2016-08-19 16-38-59](https://cloud.githubusercontent.com/assets/20875171/17808151/e9324404-65fd-11e6-832e-17f28d7c7d09.png)

**Comment by devrajashwin** [comment] 2016-08-19 11:15
its an orignal appliction 
backuped my phone apk file

**Comment by devrajashwin** [comment] 2016-08-20 13:49
Are u gona reply me or not ,

**Comment by cacaocaca** [comment] 2016-08-22 01:44
Go on backdoor-apk.sh open it with edit of text getdit or other afther ctrl + f and text "Owner" he show two line of "Owner" replace it with "Proprietario" Save Rerun and work :)

**Comment by devrajashwin** [comment] 2016-08-22 14:45
i allready try it ,
but the result is same ,
if ur are saying so i will try i once more

**Comment by devrajashwin** [comment] 2016-08-22 15:51
i think some thing is missing in this code,
plz check this when i open this backdoor apk-sh with gedit its directly take me to this code,


echo -n "[*] Signing recompiled APK..."
$JARSIGNER -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $keystore -storepass android -keypass android $compiled_apk signing.key >>$LOG_FILE 2>&1
rc=$?
echo "done."
if [ $rc != 0 ]; then
  echo "[!] Failed to sign recompiled APK"
  cleanup
  exit $rc
fi

echo -n "[*] Verifying signed artifacts..."
$JARSIGNER -verify -verbose -certs $compiled_apk >>$LOG_FILE 2>&1
rc=$?
echo "done."
if [ $rc != 0 ]; then
  echo "[!] Failed to verify signed artifacts"
  cleanup
  exit $rc
fi

mv $compiled_apk $unaligned_apk

echo -n "[*] Aligning recompiled APK..."
$ZIPALIGN -v 4 $unaligned_apk $compiled_apk >>$LOG_FILE 2>&1
rc=$?
echo "done."
if [ $rc != 0 ]; then
  echo "[!] Failed to align recompiled APK"
  cleanup
  exit $rc
fi

rm $unaligned_apk

exit 0

**Comment by simonpunk** [comment] 2016-08-23 09:52
hi, i ecountered the same issue as well, but when I look at the run.log, the line says:

rm: cannot remove 'signing.keystore': No such file or directory.

So I think that's the place keep raising the error.

**Comment by devrajashwin** [comment] 2016-08-23 10:39
yes plz post a new  isssue ,
so that they can help us

**Comment by dana-at-cp** [comment] 2016-08-23 13:16
Run the following via the command line on your Kali Linux instance inside the git cloned directory for backdoor-apk:

shell> git remote show origin

Please share the output.

**Comment by dana-at-cp** [comment] 2016-08-23 13:25
So, I noticed this in the run.log file you shared above:

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_3839462608819321650.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 18, --version-code, 674, --version-name, 2.2.9, -F, /tmp/APKTOOL7858375429182164987.tmp, -0, arsc, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/backdoor-apk/backdoor-apk/original/res, -M, /root/backdoor-apk/backdoor-apk/original/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_3839462608819321650.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 18, --version-code, 674, --version-name, 2.2.9, -F, /tmp/APKTOOL7858375429182164987.tmp, -0, arsc, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/backdoor-apk/backdoor-apk/original/res, -M, /root/backdoor-apk/backdoor-apk/original/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_3839462608819321650.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 18, --version-code, 674, --version-name, 2.2.9, -F, /tmp/APKTOOL7858375429182164987.tmp, -0, arsc, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/backdoor-apk/backdoor-apk/original/res, -M, /root/backdoor-apk/backdoor-apk/original/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:97)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_3839462608819321650.tmp": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at brut.util.OS.exec(OS.java:90)
        ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 8 more
Forcing cleanup due to a failure or error state!
```

This is an error being thrown by apktool.

**Comment by devrajashwin** [comment] 2016-08-24 11:43
root@localhost:~/backdoor-apk/backdoor-apk# git remote show origin
* remote origin
  Fetch URL: https://github.com/dana-at-cp/backdoor-apk
  Push  URL: https://github.com/dana-at-cp/backdoor-apk
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)

**Comment by dana-at-cp** [comment] 2016-08-24 15:48
Try running the cleanup.sh script before running the backdoor-apk.sh script.

**Comment by dana-at-cp** [comment] 2016-08-24 15:53
This seems to be a duplicate of another reported issue: #30 

Closing as duplicate.

**Closed by dana-at-cp** 2016-08-24 15:53 UTC
