### ISSUE TITLE
Failed to add hook

### ISSUE THREAD

**Issue by hahqmlta88** [dana-at-cp/backdoor-apk#77] opened 2017-02-06 14:29 UTC
I have tried backdooring 3 apks so far, 2 have given me the [!] Failed to locate smali file to hook bug, the last one (Pokerstars) gave me this error:

[--everything OK so far---]
> [*] Locating smali file to hook in original project...done.
> [*] Adding hook in original smali file...done.
> [!] Failed to add hook

End of run.log:

> File: /root/Desktop/backdoor-apk-master/backdoor-apk/original/smali/com/core/adkit/a.smali
> Target: "/"
> Reg: v5
> Shift count: 03
> Shift tr value: [X-ZA-Wx-za-w]
> Replacement: "03/"
> File: /root/Desktop/backdoor-apk-master/backdoor-apk/original/smali/com/core/adkit/a.smali
> Target: ""
> Reg: v0
> Shift count: 23
> Shift tr value: [D-ZA-Cd-za-c]
> Replacement: "23"
> File: /root/Desktop/backdoor-apk-master/backdoor-apk/original/smali/com/core/adkit/c.smali
> Target: "SHA-1"
> Reg: v0
> Shift count: 08
> Shift tr value: [S-ZA-Rs-za-r]
> Replacement: "08KZS-1"
> File: /root/Desktop/backdoor-apk-master/backdoor-apk/original/smali/com/core/adkit/c.smali
> Target: "WWWW"
> Reg: v0
> Shift count: 09
> Shift tr value: [R-ZA-Qr-za-q]
> Replacement: "09NNNN"
> File: /root/Desktop/backdoor-apk-master/backdoor-apk/original/smali/com/core/adkit/c.smali
> Target: "Invalid certificate"
> Reg: v1
> Shift count: 11
> Shift tr value: [P-ZA-Op-za-o]
> Replacement: "11Xckpaxs rtgixuxrpit"
> Found launcher line in manifest file: 63
> Activity lines found above launcher line: 1
> Value of android_target_activity: 
> Value of android_name: com/pyrsoftware/pokerstars/home/HomeActivity
> The launcher line appears to be within an activity element
> Value of tmp: com/pyrsoftware/pokerstars/home/HomeActivity
> The smali file to hook: /root/Desktop/backdoor-apk-master/backdoor-apk/original/smali/com/pyrsoftware/pokerstars/home/HomeActivity.smali
> Forcing cleanup due to a failure or error state!
> 

I am having issues with my connection as my country internet is really unstable, so I just downloaded the master.zip and extracted it, I am thinking maybe the zip file was corrupted from having to resume download after pause but everything seems OK.

**Comment by dana-at-cp** [comment] 2017-02-06 15:11
@hahqmlta88 I bet this is a duplicate of #75 but I'll try to confirm before closing this issue.

**Comment by dana-at-cp** [comment] 2017-02-06 15:54
@hahqmlta88 Can you attach the APK file you have?

**Comment by dana-at-cp** [comment] 2017-02-07 16:29
Closing as duplicate of #75

**Closed by dana-at-cp** 2017-02-07 16:29 UTC
Labels: duplicate

**Comment by hahqmlta88** [comment] 2017-02-09 23:22
I have got the APK on an other hard drive. Just wanted to say, after looking at #75 and decomposed the apk with apktool on that day it seems very likely it is in fact a duplicate.

**Comment by kamru** [comment] 2018-07-08 06:10
i was trying to compile cclean.apk when i got this message :
[!] Failed to add hook
