### ISSUE TITLE
application always get  ' unfortunately app has stopped ' 

### ISSUE THREAD

**Issue by maklmakl** [dana-at-cp/backdoor-apk#55] opened 2016-11-22 23:30 UTC
its always get that annoying error
i tried different apks from different sites ! 
and always get this ?
any help ?
   
![screenshot_2016-11-23-01-24-04](https://cloud.githubusercontent.com/assets/23502715/20546160/22de09fe-b11c-11e6-8070-cb1cccc4db3e.png)

**Comment by winner91** [comment] 2016-11-28 11:15
i tried many apk files from different sources I got the same problem. any idea on what's causing it  ?

**Comment by dana-at-cp** [comment] 2016-11-28 16:01
@maklmakl @winner91 Can you guys share some details of your environments? Is this Kali rolling? Are you using Metasploit that is included with Kali? Any other additional information you think might be useful.

In the meantime, I'll update my instance of Kali and test for similar issues.

**Comment by dana-at-cp** [comment] 2016-11-28 16:04
Closing as duplicate of issue: #54

**Closed by dana-at-cp** 2016-11-28 16:04 UTC
