### ISSUE TITLE
[!] Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by userdsp** [dana-at-cp/backdoor-apk#51] opened 2016-11-14 16:41 UTC
[run.log.txt](https://github.com/dana-at-cp/backdoor-apk/files/589867/run.log.txt)

**Comment by userdsp** [comment] 2016-11-16 02:38
apktool -version 2.2.1

**Comment by dana-at-cp** [comment] 2016-11-17 16:44
@userdsp Hello. Is backdoor-apk working on other APK files?

**Comment by userdsp** [comment] 2016-11-23 17:35
No. It's the same at all apk!

**Comment by userdsp** [comment] 2016-11-27 14:43
It was working before until I delete the main folder to get git clone again with the last update! Now I receive this error message :(

**Comment by userdsp** [comment] 2016-11-29 14:30
Thank you @dana-at-cp (Dwight Spencer) after you email me "did you even install the android-sdk and the android-ndk? you should do that first.
"
This message is in the past :)

**Comment by userdsp** [comment] 2016-11-29 14:53
root@kali:~/backdoor-apk/backdoor-apk# apt-get update
Hit:1 http://mirrors.netix.net/kali kali-rolling InRelease
Reading package lists... Done

root@kali:~/backdoor-apk/backdoor-apk# apt-get install lib32z1 lib32ncurses5 lib32stdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib32z1
E: Unable to locate package lib32ncurses5
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'

Maybe this is the problem?

**Comment by dana-at-cp** [comment] 2016-11-29 17:10
@userdsp There is something wrong with Apktool on your system. From your run.log file:

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_6502715368841501089.tmp, p, --forced-p$
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        at brut.androlib.Androlib.buildResources(Androlib.java:412)
        at brut.androlib.Androlib.build(Androlib.java:311)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_6502715368841501089.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-s$
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_6502715368841501089.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 7$
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
        ... 6 more
W: /tmp/brut_util_Jar_6502715368841501089.tmp: 1: /tmp/brut_util_Jar_6502715368841501089.tmp: Syntax error: "&" unexpected
```

**Comment by dana-at-cp** [comment] 2016-11-29 17:13
@userdsp Apktool does need those 32bit library packages.

https://ibotpeaches.github.io/Apktool/install/

**Comment by dana-at-cp** [comment] 2016-11-29 17:18
@userdsp I am going to close this issue since it is isolated to Apktool on your system.

**Closed by dana-at-cp** 2016-11-29 17:18 UTC

**Comment by userdsp** [comment] 2016-11-29 21:48
I have 32bit distro not 64bit,
"apktoold d test.apk" doesnt give any error!

**Comment by userdsp** [comment] 2016-11-29 21:55
root@kali:~# apktool d test.apk 
I: Using Apktool 2.2.1 on test.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

root@kali:~# apktool -version
2.2.1

**Comment by dana-at-cp** [comment] 2016-11-30 03:01
@userdsp Ah, alright. Glad you got it sorted.

**Comment by abir1937** [comment] 2017-08-03 11:51
[*] Running backdoor-apk.sh v0.2.2 on Thu Aug  3 17:49:43 +06 2017
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.1.104
[?] Please enter an LPORT value: 4444
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Decompiling original APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Running proguard on RAT APK file...done.
[*] Decompiling obfuscated RAT APK file...done.
[*] Creating new directories in original project for RAT smali files...done.
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Locating smali file to hook in original project...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

**Comment by alilord** [comment] 2017-08-03 15:39
dana-at-cp help .....???

**Comment by dana-at-cp** [comment] 2017-08-03 15:47
@alilord Couple of things:

1. You should have opened a new issue instead of commenting on a closed issue.

2. Your specific error is from Apktool and appears to be a duplicate of #78

**Comment by rocky2496** [comment] 2017-10-26 14:41
my backdoor app creating problem is
" Failed to recompile original project with backdoor"
[run.log](https://github.com/dana-at-cp/backdoor-apk/files/1418793/run.log)

please soleve  my problem

run log file
[run.log](https://github.com/dana-at-cp/backdoor-apk/files/1418798/run.log)

**Comment by rameshdevalla** [comment] 2018-07-18 04:29
Failed to build the apk after hooking and it saying it was protected apk

**Comment by new125** [comment] 2018-08-08 06:14
[!] Failed to recompile original project with backdoor


still me getting this error is this solved?? can anyone help

**Comment by FirstClickin** [comment] 2019-05-06 05:23
**🛑🛑🛑 Here is The FIX 2019..**  https://youtu.be/QfyYWioLEk4
Full Video by FirstClickin.

**Comment by justMSARahat** [comment] 2019-09-21 17:25
> root@kali:~/backdoor-apk/backdoor-apk# uname -a
> Linux kali 4.8.0-kali1-686-pae #1 SMP Debian 4.8.5-1kali1 (2016-11-04) i686 GNU/Linux
> 
> root@kali:~/backdoor-apk/backdoor-apk# apt-get update
> Hit:1 http://mirrors.netix.net/kali kali-rolling InRelease
> Reading package lists... Done
> 
> root@kali:~/backdoor-apk/backdoor-apk# apt-get install lib32z1 lib32ncurses5 lib32stdc++6
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package lib32z1
> E: Unable to locate package lib32ncurses5
> E: Unable to locate package lib32stdc++6
> E: Couldn't find any package by regex 'lib32stdc++6'
> 
> Maybehey.i have same problem.
But I notice That My linux Doesn't have installed lib32ncrses5.
And I am unable to install that,
when i type : apt-get install lib23ncrses5
the i found this: e unable to locate this package.
and this is the main problem of that.
if anyone can solve that problem???  this is the problem?

**Comment by hossamsalem23** [comment] 2019-10-21 11:31
> > root@kali:~/backdoor-apk/backdoor-apk# uname -a
> > Linux kali 4.8.0-kali1-686-pae #1 SMP Debian 4.8.5-1kali1 (2016-11-04) i686 GNU/Linux
> > root@kali:~/backdoor-apk/backdoor-apk# apt-get update
> > Hit:1 http://mirrors.netix.net/kali kali-rolling InRelease
> > Reading package lists... Done
> > root@kali:~/backdoor-apk/backdoor-apk# apt-get install lib32z1 lib32ncurses5 lib32stdc++6
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > E: Unable to locate package lib32z1
> > E: Unable to locate package lib32ncurses5
> > E: Unable to locate package lib32stdc++6
> > E: Couldn't find any package by regex 'lib32stdc++6'
> > Maybehey.i have same problem.
> > But I notice That My linux Doesn't have installed lib32ncrses5.
> > And I am unable to install that,
> > when i type : apt-get install lib23ncrses5
> > the i found this: e unable to locate this package.
> > and this is the main problem of that.
> > if anyone can solve that problem???  this is the problem?

just try apt-get install libz1 libncurses5 libstdc++6

bec your arch 32 !

**Comment by smartdickson** [comment] 2020-05-07 11:53
I am also have this error
But it is only based on apktool error!!!!

**Comment by Cat-lgtm** [comment] 2020-05-10 18:28
these are all installed. there is still a problem. back door fails

**Comment by smartdickson** [comment] 2020-05-20 11:43
you can solve it by use fatrat or decompile using ruby apk-embed-payload.rb "your apk file path"
to recombile. This method want a "apk-embed-payload.rb" file you should Download  from web.

**Comment by vinay636** [comment] 2020-05-25 06:27
![IMG_20200525_115644](https://user-images.githubusercontent.com/45120160/82784780-d97ae800-9e7e-11ea-9135-42ed183e4382.jpg)




please solve my problem
